###
POST http://localhost:3031/students/register
Content-Type: application/json

{
    "fullname": "testStudent8",
    "email": "testStudent8@gmail.com",
    "password": "testStudent8",
    "username": "testStudent8"
}

###
POST http://localhost:3031/students/login
Content-Type: application/json

{
            "username": "testStudent4",
            "password": "testStudent4"
}

###
POST http://localhost:3031/students/testStudent1/1
Content-Type: application/json

{
      "time": [[1,1,1],[1,1,1],[1,1,1]],
      "score": [[500,250,750]],
      "incat": [[1,1,1],[1,1,1],[1,1,1]],
      "badges":"bronze",
      "helpReq": false,
      "mentorUser": null
}

###
GET http://localhost:3031/students/prerana123/1

###
POST http://localhost:3031/students/getStudent
Content-Type: application/json

{
    "username": "messi1"
}

###
GET http://localhost:3031/students

###
POST http://localhost:3031/teachers/register
Content-Type: application/json

{
    "fullname": "prerana",
    "email": "prerana@gmail.com",
    "password": "prerana123",
    "username": "prerana123",
    "subject": "cs"
}

###
POST http://localhost:3031/teachers/login
Content-Type: application/json

{
    "password": "prerana123",
    "username": "prerana1234"
}