###
POST http://localhost:3031/students/register
Content-Type: application/json

{
    "fullname": "z",
    "email": "z@gmail.com",
    "password": "z",
    "username": "z"
}

###
GET http://localhost:3031/students/login
Content-Type: application/json

{
            "username": "z",
            "password": "abc"
}

###
POST http://localhost:3031/students/z/7
Content-Type: application/json

{
    "level":
    {
      "time": [[1,1],[1,1],[1,1]],
      "score": [[1,1],[1,1],[1,1]],
      "incat": [[1,1],[1,1],[1,1]]
    }
}

###
GET http://localhost:3031/students/pandey/1

###
GET http://localhost:3031/students/getStudent
Content-Type: application/json

{
    "username": "pandey"
}

###
GET http://localhost:3031/students

###
POST http://localhost:3031/teachers/register
Content-Type: application/json

{
    "fullname": "t1",
    "email": "t1@gmail.com",
    "password": "t1",
    "username": "t1",
    "subject": "cs"
}

###
GET http://localhost:3031/teachers/login
Content-Type: application/json

{
    "password": "t1",
    "username": "t1"
}